FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY UnlimitedJCEPolicyJDK8/* /⁨usr/lib/
COPY target/PhotoAppApiConfigServer-0.0.1-SNAPSHOT.jar ConfigurationServer.jar
ENTRYPOINT ["java","-jar","ConfigurationServer.jar"]
